### ISSUE TITLE
DRM Support

### ISSUE THREAD

**Issue by cruizg** [broscr/IPTV-Player#1]
I have this m3u format :

#EXTM3U
#KODIPROP:inputstream.adaptive.license_key=[licence-server]
#EXTINF:-1 group-title="Noticias",example
https://URL/example.mpd

this m3u work in DRM player support (widevine).
i put this meu in XTEVE and dont work.

help me please.
thanks

**Comment by broscr** [comment]
It doesn't support it for now but I may add it in the future.

**Comment by broscr** [comment]
now drm supported...
