### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by newerit** [broscr/IPTV-Player#10]
You help with problem?
image erro: https://ibb.co/tHYMc7Z

**Comment by broscr** [comment]
fixed error now [Commit](https://github.com/broscr/IPTV-Player/commit/6bcfb049fa9195bb894f6574d7e7484e52e00293)

**Comment by newerit** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="32" />
    <uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
    
    this is?

**Comment by broscr** [comment]
reinstall new [apk](https://github.com/broscr/IPTV-Player/blob/master/app/release/app-release.apk)
