### ISSUE TITLE
can not ready file in android 9

### ISSUE THREAD

**Issue by newerit** [broscr/IPTV-Player#14]
you can help me with this problem, i am testing in version android 9 app (mxq android)
and have thie error

in image: https://ibb.co/Tmx5qgy

**Comment by broscr** [comment]
I don't know why it doesn't work on these devices. it actually works on android 9

**Comment by newerit** [comment]
yes I find this very strange, on the device I read some questions in the android documentation to understand and everything is correct, when I use cx fileexplorer it can read the normal file and send it to the app, another strange issue would be the layout, in mxq with android9 I can't browse channels with remote
