### ISSUE TITLE
Playback Error Code 406

### ISSUE THREAD

**Issue by sradit93** [broscr/IPTV-Player#20]
ExoPlayerImplInternal:    Playback error
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:      com.google.android.exoplayer2.ExoPlaybackException: Source error
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:656)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at android.os.Handler.dispatchMessage(Handler.java:102)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at android.os.Looper.loopOnce(Looper.java:201)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at android.os.Looper.loop(Looper.java:288)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at android.os.HandlerThread.run(HandlerThread.java:67)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:      Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 406
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:419)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:269)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:90)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:105)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:68)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:179)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:420)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-24 20:47:27.246 20311 25794 E  ExoPlayerImplInternal:          at java.lang.Thread.run(Thread.java:920)

**Comment by broscr** [comment]
The error is due to receiving an HTTP response code 406, which means "Not Acceptable." This status code indicates that the server cannot produce a response matching the list of acceptable values defined in the request's headers.

This error may be related to the server. You may not be providing a source of the type supported by the project.

**Comment by sradityaa** [comment]
Source : https://nyanv-live-cdn.mncnow.id/live/eds/ANTV/sa_dash_vmx/ANTV.mpd

License : https://mrpw.ptmnc01.verspective.net/?deviceId=NDIzMDJhZmUtYWRjMi0zNGJkLTkyN2EtYmE1ZDFlZWIwODEz


Can you test it for me? So that you can find out about the problem and hope to update your source code with a new one. Thank You.

**Comment by broscr** [comment]
If you have a test file, I can try it.

**Comment by sradityaa** [comment]
[test.txt](https://github.com/broscr/IPTV-Player/files/14151624/test.txt)

Can try
