### ISSUE TITLE
All channel category

### ISSUE THREAD

**Issue by ps8303383** [broscr/IPTV-Player#4]
Please add all channel category option please sir.

**Comment by broscr** [comment]
All categories are visible. What exactly do you want?

**Comment by broscr** [comment]
> Please add all channel category option please sir.


All categories are visible. What exactly do you want?

**Comment by ps8303383** [comment]
https://drive.google.com/file/d/1GNnK3Zea31LjN62Rtij_YtTFKzGdBVzV/view?usp=drivesdk

Please watch this video 🖕🖕🖕🙏🙏

**Comment by broscr** [comment]
> https://drive.google.com/file/d/1GNnK3Zea31LjN62Rtij_YtTFKzGdBVzV/view?usp=drivesdk
> 
> Please watch this video 🖕🖕🖕🙏🙏

If you send the file format as an example by deleting the IP in it, I can look into the problem.

**Comment by ps8303383** [comment]
https://drive.google.com/file/d/1GV24VXLdcddACiOrJ2tQAnBH-gOqah3l/view?usp=drivesdk

M3u file link🖕🖕🖕

**Comment by broscr** [comment]
fixed file read. 
[`Commit`](https://github.com/broscr/IPTV-Player/commit/5f1e0e4c24a34034d22efb9164dadc01aedee2cc)

**Comment by broscr** [comment]
fixed file read.
[Commit](https://github.com/broscr/IPTV-Player/commit/5f1e0e4c24a34034d22efb9164dadc01aedee2cc)

**Comment by ps8303383** [comment]
FileSelectActivity should be open on clicking button in MainActivity.

if (new IPTvRealm().allChannelCount() > 0) {
            startActivity(new Intent(FileSelectActivity.this, MainActivity.class));
            finish();

this code is causing problems.

**Comment by ps8303383** [comment]
Please help me sir 😭😭😭
