### ISSUE TITLE
FileSelectActivity

### ISSUE THREAD

**Issue by ps8303383** [broscr/IPTV-Player#6]
FileSelectActivity should be open on clicking button in MainActivity.
Please help me.

**Comment by broscr** [comment]
You need to give permission to read files.

> FileSelectActivity should be open on clicking button in MainActivity. Please help me.

**Comment by ps8303383** [comment]
You make such an app in which we can select m3u file again and again just other iptv apps. 
your app provides just one time select m3u file. 
please make few changes your app.
