### ISSUE TITLE
The file button  is not working (Have no permission file read in settings)

### ISSUE THREAD

**Issue by ambioi** [broscr/IPTV-Player#7]
‏trouble with file select. Have no Permits

**Comment by broscr** [comment]
> ‏trouble with file select. Have no Permits

You need to give permission to read files.

**Comment by ambioi** [comment]
GrapheneOS - when I pushed the button to select the file I have alert about app permission required. I'm agree & pushing OK & then app redirect me to app permissions directory in the phone settings & its great, but.... Have no read files permission in settings. This option does not exist in the settings at all. Look in attached screenshot's


![Screenshot_20230805-050323](https://github.com/broscr/IPTV-Player/assets/141431798/5a9f785e-9f9e-4758-a502-3accfff29691)
![Screenshot_20230805-050334](https://github.com/broscr/IPTV-Player/assets/141431798/41426090-c259-4dcc-b996-e2596d8e5965)
![Screenshot_20230805-050444](https://github.com/broscr/IPTV-Player/assets/141431798/e0f743d2-80fd-42d5-aac4-6aefe4b4d2ad)
![Screenshot_20230805-050538](https://github.com/broscr/IPTV-Player/assets/141431798/2cf1af32-baf8-4ce2-81ae-8a972e7b7f21)
![Screenshot_20230805-050544](https://github.com/broscr/IPTV-Player/assets/141431798/5a83c377-2bbf-485e-9c49-565138ddff7d)
![Screenshot_20230805-050554](https://github.com/broscr/IPTV-Player/assets/141431798/b61d873a-4e59-43a5-aaf5-34ce84e9e31d)

**Comment by broscr** [comment]
it's pretty obvious that the file read permission is actually not granted. All you have to do is give the file read permission

**Comment by ambioi** [comment]
I'm sorry, I'm not clear on how to do this.

**Comment by broscr** [comment]
First app delete and reinstall

**Comment by ambioi** [comment]
Many thanks for trying for help. Unfortunately the problem is not solved by re-installation. Anyway thanks. (Same trouble have in other devices on LineageOS ROM)
