### ISSUE TITLE
Files select again and again

### ISSUE THREAD

**Issue by ps8303383** [broscr/IPTV-Player#8]
You make such an app in which we can select m3u file again and again just other iptv apps. 
your app provides just one time select m3u file. 
please make few changes your app. 😭😭😭

**Comment by broscr** [comment]
I'll do an update on this and it will be selectable again. Thank you for the feedback.

**Comment by broscr** [comment]
[added feature reselect file](https://github.com/broscr/IPTV-Player/pull/22)
